package com.bdo.bdogrcms.enums;

public enum Type {
    LAPTOP,
    WORKSTATION,
    PHYSICAL_SERVER,
    VIRTUAL_SERVER,
    HARD_COPY_DOCUMENT,
    PHYSICAL_LOCATION,
    CLOUD_SERVICE,
    _3RD_PARTY_APP,
    DATABASE,
    HARDWARE,
    INFORMATION,
    PHYSICAL_ASSET,
    BUSINESS_PROCESS,
}
